-- MySQL dump 10.13  Distrib 8.0.45, for Win64 (x86_64)
--
-- Host: localhost    Database: reliefdentalclinic
-- ------------------------------------------------------
-- Server version	8.4.8

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!50503 SET NAMES utf8 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;

--
-- Dumping data for table `roleaccess`
--

LOCK TABLES `roleaccess` WRITE;
/*!40000 ALTER TABLE `roleaccess` DISABLE KEYS */;
INSERT INTO `roleaccess` VALUES (1,'Administrator',1,1,1,1,'2026-06-01 19:31:33','2026-06-01 19:31:33',1,1,1),(2,'Doctor',1,1,1,1,'2026-06-01 19:31:33','2026-06-01 19:31:33',1,1,1),(3,'Nurse',1,1,0,0,'2026-06-01 19:31:33','2026-06-01 19:31:33',1,1,1),(4,'Patient',1,0,0,0,'2026-06-01 19:31:33','2026-06-01 19:31:33',1,1,1),(5,'Accountant',1,0,1,0,'2026-06-01 19:31:33','2026-06-01 19:31:33',1,1,1);
/*!40000 ALTER TABLE `roleaccess` ENABLE KEYS */;
UNLOCK TABLES;
--
-- Dumping data for table `emailtemplate`
--

LOCK TABLES `emailtemplate` WRITE;
/*!40000 ALTER TABLE `emailtemplate` DISABLE KEYS */;
INSERT INTO `emailtemplate` (`ID`, `TemplateId`, `Subject`, `HtmlContent`, `CreatedDate`, `ModifiedDate`, `CreatedBy`, `ModifiedBy`, `IsActive`) VALUES 
(1, 'ForgotPassword', 'Reset Your Password - {{clinic_name}}', '<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Reset Your Password</title>\n    <style>\n        body { font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif; background-color: #f7fafc; color: #2d3748; padding: 20px; margin: 0; }\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05); border: 1px solid #e2e8f0; }\n        .header { background: linear-gradient(135deg, #1a365d, #2a4365); padding: 30px; text-align: center; color: #ffffff; }\n        .header h1 { margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.5px; }\n        .content { padding: 40px 30px; line-height: 1.6; }\n        .content p { margin: 0 0 20px 0; }\n        .password-box { background-color: #ebf8ff; border: 1px solid #bee3f8; border-radius: 6px; padding: 15px; text-align: center; font-size: 22px; font-weight: bold; color: #2b6cb0; letter-spacing: 2px; margin: 30px 0; }\n        .footer { background-color: #edf2f7; padding: 20px; text-align: center; font-size: 12px; color: #718096; border-top: 1px solid #e2e8f0; }\n    </style>\n</head>\n<body>\n    <div class=\"container\">\n        <div class=\"header\">\n            <h1>{{clinic_name}}</h1>\n        </div>\n        <div class=\"content\">\n            <p>Hello {{user_name}},</p>\n            <p>We received a request to reset your password for your <strong>{{clinic_name}}</strong> account. Please use the temporary password below to log in:</p>\n            <div class=\"password-box\">\n                {{new_password}}\n            </div>\n            <p>For security reasons, we strongly recommend that you change this password immediately after logging in.</p>\n            <p>If you did not request a password reset, please ignore this email or contact us if you have any questions.</p>\n            <p>Best regards,<br>The {{clinic_name}} Team</p>\n        </div>\n        <div class=\"footer\">\n            &copy; 2026 {{clinic_name}}. All rights reserved.\n        </div>\n    </div>\n</body>\n</html>', '2026-06-13 00:00:00', '2026-06-13 00:00:00', 1, 1, 1),
(2, 'AppointmentCreated', 'Appointment Confirmed - {{clinic_name}}', '<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Appointment Confirmed</title>\n    <style>\n        body { font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif; background-color: #f7fafc; color: #2d3748; padding: 20px; margin: 0; }\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05); border: 1px solid #e2e8f0; }\n        .header { background: linear-gradient(135deg, #2c7a7b, #234e52); padding: 30px; text-align: center; color: #ffffff; }\n        .header h1 { margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.5px; }\n        .content { padding: 40px 30px; line-height: 1.6; }\n        .content p { margin: 0 0 20px 0; }\n        .details-card { background-color: #f0fff4; border: 1px solid #c6f6d5; border-radius: 6px; padding: 20px; margin: 30px 0; }\n        .details-row { display: flex; margin-bottom: 10px; border-bottom: 1px dashed #e2e8f0; padding-bottom: 10px; }\n        .details-row:last-child { margin-bottom: 0; border-bottom: none; padding-bottom: 0; }\n        .details-label { font-weight: bold; color: #22543d; width: 120px; flex-shrink: 0; }\n        .details-value { color: #2d3748; }\n        .footer { background-color: #edf2f7; padding: 20px; text-align: center; font-size: 12px; color: #718096; border-top: 1px solid #e2e8f0; }\n    </style>\n</head>\n<body>\n    <div class=\"container\">\n        <div class=\"header\">\n            <h1>Appointment Confirmed</h1>\n        </div>\n        <div class=\"content\">\n            <p>Hello {{user_name}},</p>\n            <p>Your appointment has been successfully scheduled at <strong>{{clinic_name}}</strong>. Here are the details of your visit:</p>\n            <div class=\"details-card\">\n                <div class=\"details-row\">\n                    <span class=\"details-label\">Clinic:</span>\n                    <span class=\"details-value\">{{clinic_name}}</span>\n                </div>\n                <div class=\"details-row\">\n                    <span class=\"details-label\">Date:</span>\n                    <span class=\"details-value\">{{Appointment_Date}}</span>\n                </div>\n                <div class=\"details-row\">\n                    <span class=\"details-label\">Time:</span>\n                    <span class=\"details-value\">{{Appointment_Time}}</span>\n                </div>\n            </div>\n            <p>If you need to reschedule or cancel your appointment, please contact us at least 24 hours in advance.</p>\n            <p>We look forward to seeing you!</p>\n            <p>Best regards,<br>The {{clinic_name}} Team</p>\n        </div>\n        <div class=\"footer\">\n            &copy; 2026 {{clinic_name}}. All rights reserved.\n        </div>\n    </div>\n</body>\n</html>', '2026-06-13 00:00:00', '2026-06-13 00:00:00', 1, 1, 1),
(3, 'AppointmentReminder', 'Appointment Reminder - {{clinic_name}}', '<!DOCTYPE html>\n<html>\n<head>\n    <meta charset=\"utf-8\">\n    <title>Appointment Reminder</title>\n    <style>\n        body { font-family: \"Helvetica Neue\", Helvetica, Arial, sans-serif; background-color: #f7fafc; color: #2d3748; padding: 20px; margin: 0; }\n        .container { max-width: 600px; margin: 0 auto; background-color: #ffffff; border-radius: 8px; overflow: hidden; box-shadow: 0 4px 6px rgba(0, 0, 0, 0.05); border: 1px solid #e2e8f0; }\n        .header { background: linear-gradient(135deg, #3182ce, #2b6cb0); padding: 30px; text-align: center; color: #ffffff; }\n        .header h1 { margin: 0; font-size: 24px; font-weight: 700; letter-spacing: -0.5px; }\n        .content { padding: 40px 30px; line-height: 1.6; }\n        .content p { margin: 0 0 20px 0; }\n        .details-card { background-color: #ebf8ff; border: 1px solid #bee3f8; border-radius: 6px; padding: 20px; margin: 30px 0; }\n        .details-row { display: flex; margin-bottom: 10px; border-bottom: 1px dashed #e2e8f0; padding-bottom: 10px; }\n        .details-row:last-child { margin-bottom: 0; border-bottom: none; padding-bottom: 0; }\n        .details-label { font-weight: bold; color: #2b6cb0; width: 120px; flex-shrink: 0; }\n        .details-value { color: #2d3748; }\n        .footer { background-color: #edf2f7; padding: 20px; text-align: center; font-size: 12px; color: #718096; border-top: 1px solid #e2e8f0; }\n    </style>\n</head>\n<body>\n    <div class=\"container\">\n        <div class=\"header\">\n            <h1>Appointment Reminder</h1>\n        </div>\n        <div class=\"content\">\n            <p>Hello {{user_name}},</p>\n            <p>This is a friendly reminder of your upcoming appointment at <strong>{{clinic_name}}</strong>. We look forward to your visit!</p>\n            <div class=\"details-card\">\n                <div class=\"details-row\">\n                    <span class=\"details-label\">Clinic:</span>\n                    <span class=\"details-value\">{{clinic_name}}</span>\n                </div>\n                <div class=\"details-row\">\n                    <span class=\"details-label\">Date:</span>\n                    <span class=\"details-value\">{{Appointment_Date}}</span>\n                </div>\n                <div class=\"details-row\">\n                    <span class=\"details-label\">Time:</span>\n                    <span class=\"details-value\">{{Appointment_Time}}</span>\n                </div>\n            </div>\n            <p>If you have any questions or need to make changes to your scheduled time, please contact us as soon as possible.</p>\n            <p>See you soon!</p>\n            <p>Best regards,<br>The {{clinic_name}} Team</p>\n        </div>\n        <div class=\"footer\">\n            &copy; 2026 {{clinic_name}}. All rights reserved.\n        </div>\n    </div>\n</body>\n</html>', '2026-06-13 00:00:00', '2026-06-13 00:00:00', 1, 1, 1);
/*!40000 ALTER TABLE `emailtemplate` ENABLE KEYS */;
UNLOCK TABLES;

/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2026-06-09 13:15:23
